vibe-io/cdk-extensions

.github/workflows/release.yml
.projenrc.js

Add typedoc generation to github release workflow

---

.projenrc.js

Fix a formatting issue with projenrc

---

.github/workflows/release.yml
.projenrc.js

Switch back to yarn and try setting production to false

---

.github/workflows/release.yml
.projenrc.js

Try explicitly instally typescript globally

---

.github/workflows/release.yml
.projenrc.js

Try installing typescript explicitly but not globally

---

.github/workflows/release.yml
.projenrc.js

Try running typedoc in the default github container

---

.github/workflows/release.yml
.projenrc.js

Fix a syntax issue with github workflow

---

.github/workflows/release.yml
.projenrc.js

Try a newer version of node

---

.github/workflows/release.yml
.projenrc.js

Task/typedoc GitHub job

---

.github/workflows/release.yml
.projenrc.js

Try using the configure aws credentials action to set up credentials

---

.github/workflows/release.yml
.projenrc.js

Fix issue with s3 sync command for typedoc

---

API.md
src/glue-tables/alb-logs-table.ts
src/glue-tables/cloudfront-logs-table.ts
src/glue-tables/cloudtrail-table.ts
src/glue-tables/flow-logs-table.ts
src/glue-tables/s3-access-logs-table.ts
src/glue-tables/ses-logs-table.ts
src/glue-tables/waf-logs-table.ts
src/route53resolver/resolver-rule-association.ts

Adding typedoc comments to glue-tables module

chore: Feature/glue tables typedoc

---

API.md
src/route53resolver/forward-resolver-rule.ts
src/route53resolver/inbound-resolver.ts
src/route53resolver/outbound-resolver.ts
src/route53resolver/resolver-endpoint-base.ts
src/route53resolver/resolver-rule-association.ts
src/route53resolver/resolver-rule.ts
src/route53resolver/system-resolver-rule.ts

Typedoc comments for route53resolver

chore: Feature/route53resolver typedoc

---

API.md
src/sso/assignment.ts
src/sso/group.ts
src/sso/instance-access-control-attribute-configuration.ts
src/sso/instance.ts
src/sso/lib/access-control-attribute.ts
src/sso/permission-set.ts
src/sso/user.ts

chore: Feature/sso typedoc

---

src/route53resolver/README.md

Adding route53resolver README.md

chore: adding README.md

---

API.md
src/stacks/aws-logging-stack.ts
src/stacks/index.ts

Adds typedocs for Stacks module

chore: Feature/typedoc stacks

---

.projen/deps.json
.projenrc.js
API.md
package.json
yarn.lock

feat: Update to aws cdk 2.59.0

---

API.md
src/athena/named-query.ts
src/glue/crawler.ts
src/glue/job.ts
src/glue/lib/index.ts
src/glue/lib/workflow-actions/action-base.ts
src/glue/lib/workflow-actions/crawler-action.ts
src/glue/lib/workflow-actions/index.ts
src/glue/lib/workflow-actions/job-action.ts
src/glue/lib/workflow-predicates/crawler-predicate.ts
src/glue/lib/workflow-predicates/index.ts
src/glue/lib/workflow-predicates/job-predicate.ts
src/glue/lib/workflow-predicates/predicate-base.ts
src/glue/trigger.ts
src/glue/workflow.ts

Adds basic Glue trigger actions and predicates.

feat: add trigger actions

---

API.md
src/glue/lib/workflow-predicates/crawler-predicate.ts
src/glue/lib/workflow-predicates/job-predicate.ts
src/glue/lib/workflow-predicates/predicate-base.ts

Make workflow predicate naming match naming for actions.

fix: workflow predicate consistency

---

API.md
src/glue/lib/code.ts
src/glue/lib/column.ts
src/glue/lib/workflow-actions/action-base.ts
src/glue/lib/workflow-actions/actions.ts
src/glue/lib/workflow-actions/crawler-action.ts
src/glue/lib/workflow-actions/job-action.ts
src/glue/lib/workflow-predicates/crawler-predicate.ts
src/glue/lib/workflow-predicates/job-predicate.ts
src/glue/lib/workflow-predicates/predicate-base.ts
src/glue/lib/workflow-predicates/predicate.ts

Adds helper classes and proper documentation for Glue trigger actions and predicates.

feat: Add helper classes and documentation for trigger actions and predicates

---

API.md
src/index.ts
src/rds/database-proxy-endpoint.ts
src/rds/index.ts
src/utils/types.ts

Add a basic L2 resource for RDS db proxy endpoints.

feat: Add rds proxy endpoint L2 resource

---

src/rds/database-proxy-endpoint.ts

Fixes an invalid security group description for RDS db proxy endpoints.

fix: Fix invalid security group description

---

API.md
src/athena/named-query.ts
src/index.ts
src/lambda/index.ts
src/lambda/log-retention-controller.ts

Adds the lambda log retention controller to automatically add a retention policy for log groups created by lambda.

feat: lambda log retention controller

---

API.md
package-lock.json
src/rds/database-proxy-endpoint.ts
yarn.lock

Account for a breaking change made to the CloudFormation DBProxyEndpoint resource where the previously supported TargetRole property was removed.

fix: Breaking change to DBProxyEndpoint API

---

.projen/deps.json
.projenrc.js
package-lock.json
package.json
yarn.lock

fix: Upgrade to CDK 2.66.0

---

.projen/deps.json
.projenrc.js
package.json
yarn.lock

fix: Update to aws-cdk-lib 2.69.0

---

API.md
src/ec2-patterns/index.ts

Add missing export for NetworkController.

fix: Add missing export for NetworkController controller

---

src/core/dynamic-reference-lock.ts
src/core/dynamic-reference.ts
src/core/export-parameter-provider.ts
src/core/test/dynamic-reference.test.ts

Add initial work for cross stage references.
They're pretty limited and basic for the moment but allows some simple cross stage networking.

feat: Task/basic cross stage references

---

API.md
src/ec2-patterns/network-controller.ts

Allow availability zones to be overridden in network controller.

feat: Allow users to override AZ defaults for network controller

---

API.md
src/ec2-patterns/four-tier-network-hub.ts
src/ec2-patterns/network-controller.ts
src/ec2/transit-gateway-attachment-base.ts
src/ec2/transit-gateway-route-table.ts
src/ec2/transit-gateway.ts

Add missing routes needed for tiered network connectivity

fix: Add missing routes needed for tiered network connectivity

---

API.md
src/ec2-patterns/network-isolated-client-vpn-endpoint.ts

Allow adding routes to all client vpn subnets in a single call

feat: Allow adding routes to all client vpn subnets in a single call

---

API.md
src/ec2-patterns/network-isolated-client-vpn-endpoint.ts

Expand capabilities of network isolated client vpn endpoint

feat: Expand capabilities of network isolated client vpn endpoint

---

.projen/deps.json
.projenrc.js
API.md
package.json
yarn.lock

Upgrade AWS CDK libs to 2.79.1 along with other dependencies

feat: upgrade to 2 79 1

---

.projen/deps.json
.projenrc.js
package.json
yarn.lock

feat: Upgrade to CDK 2.87.0

---

.projen/deps.json
.projenrc.js
API.md
package.json
yarn.lock

Upgrade to aws-cdk-lib v2.89.0

feat: Upgrade to aws-cdk-lib v2.89.0
